<h1><center>Quantconnect Introduction to Financial Python</center></h1>
<h2><center>Gian Emanuel Morales Gonzalez</center></h2>





#**1. Data Types and Data Structures**

## **Introduction**

This tutorial provides a basic introduction to the Python programming language. If you are new to Python, you should run the code snippets while reading this tutorial. If you are an advanced Python user, please feel free to skip this chapter.

## **Basic Variable Types**
The basic types of variables in Python are: strings, integers, floating point numbers and booleans.

Strings in python are identified as a contiguous set of characters represented in either single quotes (' ') or double quotes (" ").

In [1]:
#Ejemplo quantconnect
my_string1 = 'Welcome to'
my_string2 = "QuantConnect"
print(my_string1 + ' ' + my_string2)

Welcome to QuantConnect


In [3]:
#ejemplo propio
my_string1 = 'Gian: Este'
my_string2 = "es mi ejemplo :v"
print(my_string1 + ' ' + my_string2)

Gian: Este es mi ejemplo :v


An integer is a round number with no values after the decimal point.

In [4]:
#Ejemplo quantconnect
my_int = 10
print(my_int)
print(type(my_int))

10
<class 'int'>


In [5]:
#Ejemplo propio
my_int = 2389
print(my_int)
print(type(my_int))

2389
<class 'int'>


The built-in function int() can convert a string into an integer.

In [6]:
#Ejemplo quantconnect
my_string = "100"
print(type(my_string))
my_int = int(my_string)
print(type(my_int))

<class 'str'>
<class 'int'>


In [7]:
#Ejemplo propio
my_string = "102"
print(type(my_string))

my_int = int(my_string)
print(type(my_int))


<class 'str'>
<class 'int'>


A floating point number, or a float, is a real number in mathematics. In Python we need to include a value after a decimal point to define it as a float.

In [8]:
#Ejemplo quantconnect
my_float = 1.0
print(type(my_float))

my_int = 1
print(type(my_int))


<class 'float'>
<class 'int'>


In [10]:
#Ejemplo propio
my_float = 4.487
print(type(my_float))

my_int = 4
print(type(my_int))


<class 'float'>
<class 'int'>


As you can see above, if we don't include a decimal value, the variable would be defined as an integer. The built-in function float() can convert a string or an integer into a float.

In [11]:
#Ejemplo quantconnect
my_string = "100"
my_float = float(my_string)
print(type(my_float))


<class 'float'>


In [16]:
#Ejemplo propio
my_string = "8"
my_float = float(my_string)
print(type(my_float))


<class 'float'>


A boolean, or bool, is a binary variable. Its value can only be True or False. It is useful when we do some logic operations, which would be covered in our next chapter.

In [18]:
#Ejemplo quantconnect
my_bool = False
print(my_bool)

print(type(my_bool))


False
<class 'bool'>


In [20]:
#ejemplo propio
my_bool = True
print(my_bool)

print(type(my_bool))


False
<class 'bool'>


## **Basic Math Operations**
The basic math operators in python are demonstrated below:

In [ ]:
#Ejemplo quantconnect
print("Addition ", 1+1)
print("Subtraction ", 5-2)
print("Multiplication ", 2*3)
print("Division", 10/2)
print("exponent", 2**3)


In [22]:
#ejemplo propio
print("Addition ", 752+8)
print("Subtraction ", 55-200)
print("Multiplication ", 42*43)
print("Division", 48/35)
print("exponent", 5**4)


Addition  760
Subtraction  -145
Multiplication  1806
Division 1.3714285714285714
exponent 625


## **Data Collections**
### **_List_**
A list is an ordered collection of values. A list is mutable, which means you can change a list's value without changing the list itself. Creating a list is simply putting different comma-separated values between square brackets.

In [23]:
#Ejemplo quantconnect
my_list = ['Quant', 'Connect', 1,2,3]
print(my_list)


['Quant', 'Connect', 1, 2, 3]


In [26]:
#ejemplo propio
my_list = ['Gian', 'Algoritmos', 2021,2,3.14]
print(my_list)


['Gian', 'Algoritmos', 2021, 2, 3.14]


The values in a list are called "elements". We can access list elements by indexing. Python index starts from 0. So if you have a list of length n, the index of the first element will be 0, and that of the last element will be n − 1. By the way, the length of a list can be obtained by the built-in function len().

In [27]:
#Ejemplo quantconnet
my_list = ['Quant', 'Connect', 1,2,3]
print(len(my_list))

print(my_list[0])

print(my_list[len(my_list) - 1])


5
Quant
3


In [28]:
#ejemplo propio
my_list = ['Gian', 'Algoritmos', 2021,2,3.14,'UNAL',':)']
print(len(my_list))

print(my_list[1])

print(my_list[len(my_list) - 3])


7
Algoritmos
3.14


You can also change the elements in the list by accessing an index and assigning a new value.

In [29]:
#Ejemplo quantconnect
my_list = ['Quant','Connect',1,2,3]
my_list[2] = 'go'
print(my_list)


['Quant', 'Connect', 'go', 2, 3]


In [44]:
#Ejemplo propio
my_list = ['Gian', 'Algoritmos', 2021,2,3.14,'UNAL',':)']
my_list[1] = 'Morales'
my_list[6] = 2389
print(my_list)


['Gian', 'Morales', 2021, 2, 3.14, 'UNAL', 2389]


A list can also be sliced with a colon:

In [42]:
#Ejemplo quantconnect
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:3])


['Connect', 1]


In [46]:
#Ejemplo propio
my_list = ['Gian', 'Algoritmos', 2021,2,'inter exclu',':)']
print(my_list[0:4])


['Gian', 'Algoritmos', 2021, 2]


The slice starts from the first element indicated, but excludes the last element indicated. Here we select all elements starting from index 1, which refers to the second element:

In [41]:
#Ejemplo quantconnect
print(my_list[1:])


['Algoritmos', 2021, 2, 'inter exclu', ':)']


In [40]:
#Ejemplo propio
print(my_list[3:])

[2, 'inter exclu', ':)']


And all elements up to but excluding index 3:

In [47]:
#Ejemplo quantconnect
print(my_list[:3])

['Gian', 'Algoritmos', 2021]


In [48]:
#ejemplo propio
print(my_list[:2])

['Gian', 'Algoritmos']


If you wish to add or remove an element from a list, you can use the append() and remove() methods for lists as follows:

In [49]:
#Ejemplo quantconnect
my_list = ['Hello', 'Quant']
my_list.append('Hello')
print(my_list)

my_list.remove('Hello')
print(my_list)


['Hello', 'Quant', 'Hello']
['Quant', 'Hello']


In [50]:
#ejemplo propio
my_list = ['Hola', 'Compañeros']
my_list.append('Como')
my_list.append('estan')
print(my_list)

my_list.remove('Compañeros')
print(my_list)


['Hola', 'Compañeros', 'Como', 'estan']
['Hola', 'Como', 'estan']


When there are repeated instances of "Hello", the first one is removed.

### **_Tuple_**
A tuple is a data structure type similar to a list. The difference is that a tuple is immutable, which means you can't change the elements in it once it's defined. We create a tuple by putting comma-separated values between parentheses.

In [51]:
#Ejemplo quantconnect
my_tuple = ('Welcome','to','QuantConnect')

In [52]:
#Ejemplo propio
my_tuple = ('Bienvenido','ª','Algoritmos')

Just like a list, a tuple can be sliced by using index.

In [53]:
#Ejemplo quantconnect
my_tuple = ('Welcome','to','QuantConnect')
print(my_tuple[1:])

('to', 'QuantConnect')


In [54]:
#Ejemplo propio
my_tuple = ('Bienvenido','ª','Algoritmos')
print(my_tuple[1:])

('ª', 'Algoritmos')


### **_Set_**
A set is an **_unordered_** collection with **_no duplicate_** elements. The built-in function set() can be used to create sets.

In [55]:
#Ejemplo quantconnect
stock_list = ['AAPL','GOOG','IBM','AAPL','IBM','FB','F','GOOG']
stock_set = set(stock_list)
print(stock_set)

{'FB', 'F', 'GOOG', 'AAPL', 'IBM'}


In [56]:
#Ejemplo propio
stock_list = ['Algoritmos','UNAL','Gian','Morales','UNAL','Algoritmos','F','GOOG']
stock_set = set(stock_list)
print(stock_set)

{'Algoritmos', 'Gian', 'F', 'GOOG', 'UNAL', 'Morales'}


***Set is an easy way to remove duplicate elements from a list.***

### **_Dictionary_**
A dictionary is one of the most important data structures in Python. Unlike sequences which are indexed by integers, dictionaries are indexed by keys which can be either strings or floats.

A dictionary is an **_unordered_** collection of key : value pairs, with the requirement that the keys are unique. We create a dictionary by placing a comma-separated list of key : value pairs within the braces.

In [60]:
#Ejemplo quantconnect
my_dic_q = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}

In [64]:
#Ejemplo propio
my_dic_p = {'ALG':'Algoritmos', 'GEMG':'Gian', '3165000':'UNAL'}

After defining a dictionary, we can access any value by indicating its key in brackets.


In [62]:
#Ejemplo quantconnect
print(my_dic_q['GOOG'])

Alphabet


In [65]:
#Ejemplo propio
print(my_dic_p['3165000'])

UNAL


We can also change the value associated with a specified key:

In [69]:
#Ejemplo quantconnect
my_dic_q['GOOG'] = 'Alphabet Company'
print(my_dic_q['GOOG'])

Alphabet Company


In [70]:
#Ejemplo propio
my_dic_p['ALG'] = 'unalAlgoritmos'
print(my_dic_p['ALG'])

unalAlgoritmos


The built-in method of the dictionary object dict.keys() returns a list of all the keys used in the dictionary.

In [71]:
#Ejemplo quantconnect
print(my_dic_q.keys())

dict_keys(['AAPL', 'FB', 'GOOG'])


In [72]:
#Ejemplo propio
print(my_dic_p.keys())

dict_keys(['ALG', 'GEMG', '3165000'])


## **Common String Operations** ##
A string is an immutable sequence of characters. It can be sliced by index just like a tuple:

In [74]:
#Ejemplo quantconnect
my_str = 'Welcome to QuantConnect'
print(my_str[8:])

to QuantConnect


In [81]:
#Ejemplo propio
my_str = 'UNAL Algoritmos 2021'
print(my_str[4:])

 Algoritmos 2021


There are many methods associated with strings. We can use **_string.count()_** to count the occurrences of a character in a string, use **_string.find()_** to return the index of a specific character, and use **_string.replace()_** to replace characters.

In [82]:
#Ejemplo quantconnect
print("Counting the number of e's in this sentence".count('e'))

print('The first time e appears in this sentence'.find('e'))

print('all the a in this sentence now becomes e'.replace('a','e'))


6
2
ell the e in this sentence now becomes e


In [85]:
#ejemplo propio
print("Pedro Perez Pereira pobre pintor portugues".count('p'))

print('pinta Preciosos paisaje '.find('P'))

print('Para poder partir para Paris'.replace('p','l'))


3
6
Para loder lartir lara Paris


The most commonly used method for strings is **_string.split()_**. This method will split the string by the indicated character and return a list:

In [93]:
#Ejemplo quantconnect 
Time = '2016-04-01 09:43:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)

hour = time.split(':')[0]
print(hour)


2016-04-01 09:43:00
09


In [92]:
#ejemplo propio
Time = '2016-12-25 09:43:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)

minute = time.split(':')[1]
mes = date.split('-')[1]
dia = date.split('-')[2]
print(minute, mes, dia)


2016-12-25 09:43:00
43 12 25


We can replace parts of a string by our variable. This is called string formatting.

In [94]:
#Ejemplo quantconnect
my_time = 'Hour: {}, Minute: {}'.format(9, 43)
print(my_time)

Hour: 9, Minute: 43


In [96]:
#ejemplo propio
my_date = 'year: {}, mes: {}, dia: {}'.format(2021, 'oct', 16)
print(my_date)

year: 2021, mes: oct, dia: 16


Another way to format a string is to use the % symbol.

In [99]:
#Ejemplo quantconnect
print('pi is %f' % 3.14)

print('%s to %s' % ('Welcome', 'QuantConnect'))


pi is 3.140000
Welcome to QuantConnect


In [105]:
#ejemplo propio
print('la suma de e y pi es %f' % 5.8598)

print('%s a la clase de %s' % ('Bienvenido', 'Algoritmos'))


la suma de e y pi es 5.859800
Bienvenido a la clase de Algoritmos


%s is a placeholder that takes in a string. Similarly %f takes a float and %d takes an integer.

### **Summary**
We have seen the basic data types and data structures in Python. It's important to keep practicing to become familiar with these data structures. In the next tutorial, we will cover for and while loops and logical operations in Python.

#**2. Logical Operations and Loops**
## **Introduction**
We discussed the basic data types and data structures in Python in the last tutorial. This chapter covers logical operations and loops in Python, which are very common in programming.

## **Logical Operations**
Like most programming languages, Python has comparison operators:

In [107]:
#Ejemplo quantconnect
print(1 == 0)    # 1 equals 0
print(1 == 1)    # 1 equals 1
print(1 != 0)   # 1 is not equal to 0
print(5 >= 5)    # 5 is greater than or equal to 5
print(5 >= 6)    # 5 is greater than or equal to 6


False
True
True
True
False


In [108]:
#ejemplo propio
print(1 == 1)    
print("d" == "s") 
print(1 != 0)    
print(8 >= 1)    
print('s' < 'a')   

True
False
True
True
True


Each statement above has a boolean value, which must be either True or False, but not both.

We can combine simple statements P and Q to form complex statements using logical operators:

* The statement **"P and Q"** is true if both P and Q are true, otherwise it is false.
* The statement **"P or Q"** is false if both P and Q are false, otherwise it is true.
* The statement **"not P"** is true if P is false, and vice versa.

In [110]:
#Ejemplo quantconnect
print(2 > 1 and 3 > 2)
print(2 > 1 and 3 < 2)
print(2 > 1 or  3 < 2)
print(2 < 1 and 3 < 2)

True
True
True
False


In [117]:
#ejemplo propio
print('a' > 'A' and 8 > 7)
print(52 >= 52 and 45 < 68)
print(554 <= 74 or  'M' < 'v')
print(3.54 < 3.55 and 1 < 7)

True
True
True
True


When dealing with a very complex logical statement that involves in several statements, we can use brackets to separate and combine them.



In [127]:
#Ejemplo quantconnect
print((3 > 2 or 1 < 3) and (1!=3 and 4>3) and not (3 < 2 or 1 < 3 and (1!=3 and 4>3)))
print(3 > 2 or 1 < 3 and (1!=3 and 4>3) and not (3 < 2 or 1 < 3 and (1!=3 and 4>3)))


False
True


In [130]:
#ejemplo propio
print(9 > 2 or (1 < 3 and 1!=3 and 4>3) and not (3 < 2 or 1 < 3 and (1!=3 and 4>3)))
print(3 > 2 or 1 < 3 and (1!=3 and 4>3 and not (5 < 5 or 1 < 3) and 3!=3) and 4>3)


True
True


Comparing the above two statements, we can see that it's wise to use brackets when we make a complex logical statement.

## **If Statement**
An if statement executes a segment of code only if its condition is true. A standard if statement consists of 3 segments: if, elif and else.


```
if condition1:
    # if condition1 is true, execute the code here
    # and ignore the rest of this if statement
elif condition2:
    # if condition1 is false, and condition2 is true, execute the code here
    # and ignore the rest of this if statement
else:
    # if none of the above conditions is True, execute the code here
```
An if statement doesn't necessarily has elif and else part. If it's not specified, the indented block of code will be executed when the condition is true, otherwise the whole if statement will be skipped.


In [132]:
#Ejemplo quantconnect
i = 0
if i == 0: print('i == 0 is True')


i == 0 is True


In [134]:
#ejemplo propio
i = 'truth'
if i == 'truth': print('i es verdad')


i es verdad


As we mentioned above, we can write some complex statements here:



In [135]:
#Ejemplo quantconnect
p = 1 > 0
q = 2 > 3
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

q is false


In [137]:
#ejemplo propio
p = 8 > 8
q = 1 >= 3
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

None of p and q is true


## **Loop Structure**
Loops are an essential part of programming. The "for" and "while" loops run a block of code repeatedly.

### **_While Loop_**
A "while" loop will run repeatedly until a certain condition has been met.

In [139]:
#Ejemplo quantconnect
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


In [141]:
#Ejemplo propio
i = 5
while i >= 0:
    print(i)
    i -= 1

5
4
3
2
1
0


When making a while loop, we need to ensure that something changes from iteration to iteration so that the while loop will terminate, otherwise, it will run forever. Here we used i += 1 (short for i = i + 1) to make i larger after each iteration. This is the most commonly used method to control a while loop.

### **_For Loop_**
A "for" loop will iterate over a sequence of value and terminate when the sequence has ended.

In [142]:
#Ejemplo quantconnect
for x in [1,2,3,4,5]: print(x)

1
2
3
4
5


In [152]:
#Ejemplo propio
for x in range(6): print(x)

0
1
2
3
4
5


We can also add if statements in a for loop. Here is a real example from our pairs trading algorithm:

In [147]:
#Ejemplo quantconnect
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print(new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [155]:
#ejemplo propio
numbers = [4,5,6,7,6,8,1,9,5]
selected_numbers = [5,1]
new_num_list = []
for number in numbers:
    if number not in selected_numbers:
        new_num_list.append(number)
print(numbers)
print(new_num_list)

[4, 5, 6, 7, 6, 8, 1, 9, 5]
[4, 6, 7, 6, 8, 9]


Here we iterated all the elements in the list 'stocks'. Later in this chapter, we will introduce a smarter way to do this, which is just a one-line code.

### **_Break and continue_**
These are two commonly used commands in a for loop. If "break" is triggered while a loop is executing, the loop will terminate immediately:

In [ ]:
#Ejemplo quantconnect
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    print(stock)
    if stock == 'FB': break

In [157]:
#Ejemplo propio
numbers = [4,5,5,6,6,4,0,9,6,5,5]
for number in numbers:
    print(number)
    if number == 0:
      break

4
5
5
6
6
4
0


The "continue" command tells the loop to end this iteration and skip to the next iteration:

In [5]:
#Ejemplo quantconnect
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    if stock == 'FB': continue
    print(stock)

AAPL
GOOG
IBM
F
V
G
GE


In [4]:
#Ejemplo propio
numbers = [4,5,5,6,6,4,0,9,6,5,5]
for number in numbers:
    if number == 0: 
      continue
    print(number)

4
5
5
6
6
4
9
6
5
5


## **list Comprehension**
List comprehension is a Pythonic way to create lists. Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence. For example, if we want to create a list of squares using for loop:

In [6]:
#Ejemplo quantconnect
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**2)
print(squares)

[1, 4, 9, 16, 25]


In [10]:
#Ejemplo propio
abc = []
for i in ['a','b','c','d','e','f']:
    abc.append(i*3)
print(abc)

['aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff']


Using list comprehension:

In [11]:
#Ejemplo quantconnect
foo = [1,2,3,4,5]
squares = [x**2 for x in foo]
print(squares)

[1, 4, 9, 16, 25]


In [12]:
#Ejemplo propio
until_f = ['a','b','c','d','e','f']
abc = [x*3 for x in until_f]
print(abc)

['aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff']


Recall the example above where we used a for loop to select stocks. Here we use list comprehension:

In [14]:
#Ejemplo quantconnect
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = [x for x in stocks if x not in selected]
print(new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [13]:
#ejemplo propio
numbers = [4,5,6,7,6,8,1,9,5]
selected_numbers = [5,1]
new_num_list = [x for x in numbers if x not in selected_numbers]

print(numbers)
print(new_num_list)

[4, 5, 6, 7, 6, 8, 1, 9, 5]
[4, 6, 7, 6, 8, 9]


A list comprehension consists of square brackets containing an expression followed by a "for" clause, and possibly "for" or "if" clauses. For example:

In [15]:
#Ejemplo quantconnect
print([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','FB'] for y in ['F','V','G','GE'] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['AAPL vs F', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs F', 'GOOG vs V', 'GOOG vs G', 'GOOG vs GE', 'IBM vs F', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'FB vs F', 'FB vs V', 'FB vs G', 'FB vs GE']


In [18]:
#Ejemplo quantconnect
print([(x, y) for x in ['a','b'] for y in [1,2,3,4,5,6] if x != y])

print([str(x) + ' vs ' + str(y) for x in ['COL','ECU','BRA'] for y in ['CHI','ARG','URU','BRA'] if x != y])

[('a', 1), ('a', 2), ('a', 3), ('a', 4), ('a', 5), ('a', 6), ('b', 1), ('b', 2), ('b', 3), ('b', 4), ('b', 5), ('b', 6)]
['COL vs CHI', 'COL vs ARG', 'COL vs URU', 'COL vs BRA', 'ECU vs CHI', 'ECU vs ARG', 'ECU vs URU', 'ECU vs BRA', 'BRA vs CHI', 'BRA vs ARG', 'BRA vs URU']


List comprehension is an elegant way to organize one or more for loops when creating a list.

### **Summary**
This chapter has introduced logical operations, loops, and list comprehension. In the next chapter, we will introduce functions and object-oriented programming, which will enable us to make our codes clean and versatile.

# **3. Functions and Objective-Oriented Programming**
## **Introduction**
In the last tutorial we introduced logical operations, loops and list comprehension. We will introduce functions and object-oriented programming in this chapter, which will enable us to build complex algorithms in more flexible ways.

## **Functions**
A function is a reusable block of code. We can use a function to output a value, or do anything else we want. We can easily define our own function by using the keyword "def".

In [19]:
#Ejemplo quantconnect
def product(x,y):
    return x*y
print(product(2,3))

print(product(5,10))


6
50


In [23]:
#Ejemplo propio
def suma(x,y):
    return x+y
print(suma(56,44))

print(suma(5,14))


100
19


The keyword "def" is followed by the function name and the parenthesized list of formal parameters. The statements that form the body of the function start at the next line, and must be indented. The product() function above has "x" and "y" as its parameters. A function doesn't necessarily have parameters:

In [25]:
#Ejemplo quantconnect
def say_hi():
    print('Welcome to QuantConnect')
say_hi()

Welcome to QuantConnect


In [27]:
#Ejemplo propio
def UNAL_hi():
    print('Universidad Nacional de Colombia')
UNAL_hi()

Universidad Nacional de Colombia


## **Built-in Function**
**_range()_** is a function that creates a list containing an arithmetic sequence. It's often used in for loops. The arguments must be integers. If the "step" argument is omitted, it defaults to 1.

In [29]:
#Ejemplo quantconnect
print(range(10))

print(range(1, 11))

print(range(1, 11, 2))


range(0, 10)
range(1, 11)
range(1, 11, 2)


In [37]:
#Ejemplo propio
print(range(15))

print(range(5, 20))

print(range(6, 35, 3))


range(0, 15)
range(5, 20)
range(6, 35, 3)


**_len()_** is another function used together with range() to create a for loop. This function returns the length of an object. The argument must be a sequence or a collection.

In [39]:
#Ejemplo quantconnect
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
print("The number of tickers is {}".format(len(tickers)))
for k in range(len(tickers)):
    print(k + 1, tickers[k])

The number of tickers is 8
1 AAPL
2 GOOGL
3 IBM
4 FB
5 F
6 V
7 G
8 GE


In [1]:
#ejemplo propio
letters = ['a','b','c','d','e','f']
print("The number of letters is {}".format(len(letters)))
for i in range(len(letters)):
    print(i + 1, letters[i])

The number of letters is 6
1 a
2 b
3 c
4 d
5 e
6 f


Note: If you want to print only the tickers without those numbers, then simply write "for ticker in tickers: print ticker"

**_map()_** is a function that applies a specific function to every item of a sequence or collection, and returns a list of the results.

In [4]:
#Ejemplo quantconnect
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print(list(map(len,tickers)))

[4, 4, 3, 2, 1, 1, 1, 2]


In [5]:
#ejemplo propio
words = ['ant','bee','cold','dust','exit','fork']
print(list(map(len,words)))

[3, 3, 4, 4, 4, 4]


The **_lambda operator_** is a way to create small anonymous functions. These functions are just needed where they have been created. For example:

In [7]:
#Ejemplo quantconnect
list(map(lambda x: x**2, range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [10]:
#Ejemplo propio
list(map(lambda x: (x+x)*x, range(10)))

[0, 2, 8, 18, 32, 50, 72, 98, 128, 162]

map() can be applied to more than one list. The lists have to have the same length.

In [13]:
#Ejemplo quantconnect
list(map(lambda x, y: x+y, [1,2,3,4,5], [5,4,3,2,1]))

[6, 6, 6, 6, 6]

In [14]:
#Ejemplo propio
list(map(lambda x, y: x**y, [1,2,3,4,5], [5,4,3,2,1]))

[1, 16, 27, 16, 5]

**_sorted()_** takes a list or set and returns a new sorted list:

In [15]:
#Ejemplo quantconnect
sorted([5,2,3,4,1])

[1, 2, 3, 4, 5]

In [18]:
#Ejemplo propio
sorted(['i','u','o','e','a'], reverse=True)

['u', 'o', 'i', 'e', 'a']

We can add a "key" parameter to specify a function to be called on each list element prior to making comparisons. For example:

In [24]:
#Ejemplo quantconnect
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1])


[('MSFT', 69),
 ('WMT', 75.32),
 ('AAPL', 144.09),
 ('FB', 150),
 ('GOOGL', 911.71)]

In [27]:
#Ejemplo propio
subject_list = [('ALG', 211), ('MUN', 212), ('M&S', 213), ('PHI', 214), ('GGP', 215)]
sorted(subject_list, key = lambda x: x[1])


[('ALG', 211), ('MUN', 212), ('M&S', 213), ('PHI', 214), ('GGP', 215)]

By default the values are sorted by ascending order. We can change it to descending by adding an optional parameter "reverse'.

In [ ]:
#Ejemplo quantconnect
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1], reverse=True)

In [ ]:
#Ejemplo propio
subject_list = [('ALG', 211), ('MUN', 212), ('M&S', 213), ('PHI', 214), ('GGP', 215)]
sorted(subject_list, key = lambda x: x[1], reverse=True)

Lists also have a function list.sort(). This function takes the same "key" and "reverse" arguments as sorted(), but it doesn't return a new list.

In [28]:
#Ejemplo quantconnect
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
price_list.sort(key = lambda x: x[1])
print(price_list)

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]


In [29]:
#Ejemplo propio
subject_list = [('ALG', 211), ('MUN', 212), ('M&S', 213), ('PHI', 214), ('GGP', 215)]
subject_list.sort(key=lambda x: x[1])
print(subject_list)

[('ALG', 211), ('MUN', 212), ('M&S', 213), ('PHI', 214), ('GGP', 215)]


## **Object-Oriented Programming**
Python is an object-oriented programming language. It's important to understand the concept of "objects" because almost every kind of data from QuantConnect API is an object.

### **_Class_**
A class is a type of data, just like a string, float, or list. When we create an object of that data type, we call it an **_instance_** of a class.

In Python, everything is an object - everything is an instance of some class. The data stored inside an object are called **_attributes_**, and the functions which are associated with the object are called **_methods_**.

For example, as mentioned above, a list is an object of the "list" class, and it has a method list.sort().

We can create our own objects by defining a class. We would do this when it's helpful to group certain functions together. For example, we define a class named "Stock" here:

In [31]:
#Ejemplo quantconnect
class Stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1

    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print(self.rate_return)

In [45]:
#Ejemplo propio
class Student:
  def __init__(self, ID, name, age):
    self.ID = ID
    self.name = name
    self.age = age
    
  def update_s(self, ID, age):
    self.ID = ID
    self.age = age

The "Stock" class has attributes "ticker", "open", "close", "volume" and "rate_return". Inside the class body, the first method is called __init__, which is a special method. When we create a new instance of the class, the __init__ method is immediately executed with all the parameters that we pass to the "Stock" object. The purpose of this method is to set up a new "Stock" object using data we have provided.

Here we create two Stock objects named "apple" and "google".

In [33]:
#Ejemplo quantconnect
apple  = Stock('AAPL', 143.69, 144.09, 20109375)
google = Stock('GOOGL', 898.7, 911.7, 1561616)

In [46]:
#Ejemplo propio
Juan = Student(123,'Juan Gonzalez', 15)
Juana = Student(321,'Juana Rodriguez', 16)


Stock objects also have two other methods: update() and print_return(). We can access the attribues of a Stock object and call its methods:

In [37]:
#Ejemplo quantconnect
apple.ticker

google.print_return()

google.update(912.8, 913.4)
google.print_return()

0.014465338822744034
0.0006573181419806673


In [49]:
#Ejemplo propio
print(Juan.age)
Juan.update_s(789,19)
print(Juan.age)

15
19



By calling the update() function, we updated the open and close prices of a stock. Please note that when we use the attributes or call the methods inside a class, we need to specify them as self.attribute or self.method(), otherwise Python will deem them as global variables and thus raise an error.

We can add an attribute to an object anywhere:

In [50]:
#Ejemplo quantconnect
apple.ceo = 'Tim Cook'
apple.ceo

'Tim Cook'

In [52]:
#Ejemplo propio
Juan.address = 'calle falsa 123'
Juan.address 

'calle falsa 123'

We can check what names (i.e. attributes and methods) are defined on an object using the dir() function:

In [53]:
#Ejemplo quantconnect
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [54]:
dir(Juan)

['ID',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'address',
 'age',
 'name',
 'update_s']

### **_Inheritance_**
Inheritance is a way of arranging classes in a hierarchy from the most general to the most specific. A "child" class is a more specific type of a "parent" class because a child class will inherit all the attribues and methods of its parent. For example, we define a class named "Child" which inherits "Stock":

In [55]:
#Ejemplo quantconnect
class Child(Stock):
    def __init__(self, name):
        self.name = name

In [58]:
#ejemplo propio
class ForeignStudent(Student):
  def __init__(self,country):
    self.country = country

Then we create an object:

In [59]:
#Ejemplo quantconnect
aa = Child('AA')
print(aa.name)

aa.update(100, 102)
print(aa.open)

print(aa.close)

print(aa.print_return())


AA
100
102
0.020000000000000018
None


In [66]:
#ejemplo propio
Esteban = ForeignStudent('España')
print(Esteban.country)

Esteban.update_s(109, 18)
print(Esteban.age)
print(Esteban.ID)

España
18
109


As seen above, the new class Child has inherited the methods from Stock.

###**Summary**
In this chapter we have introduced functions and classes. When we write a QuantConnect algorithm, we would define our algorithm as a class (QCAlgorithm). This means our algorithm inherited the QC API methods from QCAlgorithm class.

In the next chapter, we will introduce NumPy and Pandas, which enable us to conduct scientific calculations in Python.

# **4. NumPy and Basic Pandas**
## **Introduction**
Now that we have introduced the fundamentals of Python, it's time to learn about NumPy and Pandas.

## **NumPy**
NumPy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. It also has strong integration with Pandas, which is another powerful tool for manipulating financial data.

Python packages like NumPy and Pandas contain classes and methods which we can use by importing the package:

In [51]:
import numpy as np


### **_Basic NumPy Arrays_**
A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. Here we make an array by passing a list of Apple stock prices:

In [71]:
#Ejemplo quantconnect
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array)

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [72]:
#Ejemplo propio
cha_list = ['a', '6', '3', 'b', '5', 'v']
cha_array = np.array(cha_list)
print(cha_array, type(cha_array))

['a' '6' '3' 'b' '5' 'v'] <class 'numpy.ndarray'>


Notice that the type of array is "ndarray" which is a multi-dimensional array. ***If we pass np.array() a list of lists, it will create a 2-dimensional array.***

In [77]:
#Ejemplo quantconnect
Ar = np.array([[1,3], [2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [75]:
#Ejemplo propio
ndarr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(ndarr, type(ndarr))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


We get the dimensions of an ndarray using the .shape attribute:

In [78]:
#Ejemplo quantconnect
print(Ar.shape)

(2, 2)


In [79]:
#Ejemplo propio
print(ndarr.shape)

(3, 3)


If we create an 2-dimensional array (i.e. matrix), each row can be accessed by index:

In [81]:
#Ejemplo quantconnect
print(Ar[0])

print(Ar[1])

[1 3]
[2 4]


In [83]:
#Ejemplo propio
print(ndarr[0])

print(ndarr[2])

[1 2 3]
[7 8 9]


If we want to access the matrix by column instead:

In [84]:
#Ejemplo quantconnect
print('First column:', Ar[:,0])

print('Second column:', Ar[:,1])

First column: [1 2]
Second column: [3 4]


In [86]:
#Ejemplo propio
print('second column:', ndarr[:,1])

print('Third column:', ndarr[:,2])

second column: [2 5 8]
Third column: [3 6 9]


### **_Array Functions_**

Some functions built in NumPy that allow us to perform calculations on arrays. For example, we can apply the natural logarithm to each element of an array:

In [87]:
#Ejemplo quantconnect
np.log(price_array)

array([4.96793654, 4.98244156, 4.9675886 , 4.96995218, 4.96633504,
       4.96018375])

In [90]:
#Ejemplo propio
np.log(ndarr[1])

array([1.38629436, 1.60943791, 1.79175947])

Other functions return a single value:

In [95]:
#Ejemplo quantconnect
np.mean(price_array)

print(np.std(price_array))

print(np.sum(price_array))

print(np.max(price_array))


0.9673790478515796
863.38
145.83


In [96]:
#Ejemplo propio
np.mean(ndarr[2])

print(np.std(ndarr[2])) #standard deviation

print(np.sum(ndarr[2]))

print(np.max(ndarr[2]))


0.816496580927726
24
9


The functions above return the mean, standard deviation, total and maximum value of an array.

## **Pandas**
Pandas is one of the most powerful tools for dealing with financial data. First we need to import Pandas:

In [3]:
import pandas as pd

### **_Series_**
Series is a one-dimensional labeled array capable of holding any data type (integers, strings, float, Python object, etc.)

We create a Series by calling pd.Series(data), where data can be a dictionary, an array or just a scalar value.

In [4]:
#Ejemplo quantconnect
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print(s)


0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [5]:
#Ejemplo propio
num_flo = [1.2, 2.3, 3.4, 4.52, 4.65, 5.67]
se = pd.Series(num_flo)
print(se)

0    1.20
1    2.30
2    3.40
3    4.52
4    4.65
5    5.67
dtype: float64


We can customize the indices of a new Series:



In [6]:
#Ejemplo quantconnect
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print(s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [7]:
#Ejemplo propio
se = pd.Series(num_flo, index = [-1, -2, -3, -4, -5, -6])
print(se)

-1    1.20
-2    2.30
-3    3.40
-4    4.52
-5    4.65
-6    5.67
dtype: float64


Or we can change the indices of an existing Series:

In [8]:
#Ejemplo quantconnect
s.index = [6,5,4,3,2,1]
print(s)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64


In [9]:
#Ejemplo propio
se.index = ['*','!','*','!','*','!']
print(se)

*    1.20
!    2.30
*    3.40
!    4.52
*    4.65
!    5.67
dtype: float64


Series is like a list since it can be sliced by index:



In [10]:
#Ejemplo quantconnect
print(s[1:])
print(s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [18]:
#Ejemplo propio
print(se[2:])
print(se[:-4])

*    3.40
!    4.52
*    4.65
!    5.67
dtype: float64
*    1.2
!    2.3
dtype: float64


Series is also like a dictionary whose values can be set or fetched by index label:

In [19]:
#Ejemplo quantconnect 
print(s[4])
s[4] = 0
print(s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [20]:
#Ejemplo propio
print(se[4])
se[3] = 20
print(se)

4.65
*     1.20
!     2.30
*     3.40
!    20.00
*     4.65
!     5.67
dtype: float64


Series can also have a name attribute, which will be used when we make up a Pandas DataFrame using several series.

In [21]:
#Ejemplo quantconnect
s = pd.Series(price, name = 'Apple Prices')
print(s)
print(s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64
Apple Prices


In [22]:
#Ejemplo propio
se = pd.Series(num_flo, name = 'numeros flotantes y entero')
print(se)
print(se.name)

0    1.20
1    2.30
2    3.40
3    4.52
4    4.65
5    5.67
Name: numeros flotantes y entero, dtype: float64
numeros flotantes y entero


We can get the statistical summaries of a Series:

In [23]:
#Ejemplo quantconnect
print(s.describe())


count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Prices, dtype: float64


In [24]:
#Ejemplo propio
print(se.describe())

count    6.000000
mean     3.623333
std      1.656535
min      1.200000
25%      2.575000
50%      3.960000
75%      4.617500
max      5.670000
Name: numeros flotantes y entero, dtype: float64


### **_Time Index_**
Pandas has a built-in function specifically for creating date indices: pd.date_range(). We use it to create a new index for our Series:

In [38]:
#Ejemplo quantconnect
time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64


In [45]:
#Ejemplo quantconnect
time_index = pd.date_range('2021-10-22', periods = len(se), freq = 'M')#freq = year/month/day 
print(time_index)
se.index = time_index
print(se)

DatetimeIndex(['2021-10-31', '2021-11-30', '2021-12-31', '2022-01-31',
               '2022-02-28', '2022-03-31'],
              dtype='datetime64[ns]', freq='M')
2021-10-31    1.20
2021-11-30    2.30
2021-12-31    3.40
2022-01-31    4.52
2022-02-28    4.65
2022-03-31    5.67
Freq: M, Name: numeros flotantes y entero, dtype: float64


Series are usually accessed using the iloc[] and loc[] methods. iloc[] is used to access elements by integer index, and loc[] is used to access the index of the series.

iloc[] is necessary when the index of a series are integers, take our previous defined series as example:

In [31]:
#Ejemplo quantconnect
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
142.62


In [32]:
#Ejemplo propio
se.index = [1,2,3,4,5,6]
print(se)
print(se[1])

1    1.20
2    2.30
3    3.40
4    4.52
5    4.65
6    5.67
Name: numeros flotantes y entero, dtype: float64
1.2


If we intended to take the second element of the series, we would make a mistake here, because the index are integers. In order to access to the element we want, we use iloc[] here:

In [35]:
#Ejemplo quantconnect
print(s.iloc[1])

145.83


In [36]:
#Ejemplo propio
print(se.iloc[4])

4.65


While working with time series data, we often use time as the index. Pandas provides us with various methods to access the data by time index.



In [39]:
#Ejemplo quantconnect
s.index = time_index
print(s['2017-01-03'])

143.68


In [46]:
#Ejemplo propio
se.index = time_index
print(se['2021-12-31'])

3.4


We can even access to a range of dates:

In [47]:
#Ejemplo quantconnect
print(s['2017-01-02':'2017-01-05'])


2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64


In [50]:
#Ejemplo propio
print(se['2021-11-30':'2022-02-28'])

2021-11-30    2.30
2021-12-31    3.40
2022-01-31    4.52
2022-02-28    4.65
Freq: M, Name: numeros flotantes y entero, dtype: float64


Series[] provides us a very flexible way to index data. We can add any condition in the square brackets:

In [52]:
#Ejemplo quantconnect
print(s[s < np.mean(s)])
print(s[(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Prices, dtype: float64
2017-01-04    144.02
Freq: D, Name: Apple Prices, dtype: float64


In [60]:
#Ejemplo propio
print(se[se > np.mean(se)])
print(se[(se > np.mean(se)) | (se < np.mean(se) + 1.64*np.std(se))])

2022-01-31    4.52
2022-02-28    4.65
2022-03-31    5.67
Freq: M, Name: numeros flotantes y entero, dtype: float64
2021-10-31    1.20
2021-11-30    2.30
2021-12-31    3.40
2022-01-31    4.52
2022-02-28    4.65
2022-03-31    5.67
Freq: M, Name: numeros flotantes y entero, dtype: float64


As demonstrated, we can use logical operators like & (and), | (or) and ~ (not) to group multiple conditions.

### **Summary**
Here we have introduced NumPy and Pandas for scientific computing in Python. In the next chapter, we will dive into Pandas to learn resampling and manipulating Pandas DataFrame, which are commonly used in financial data analysis.